_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 1440
cpus_per_task: 1
tasks_per_node: 1
mem_gb: null
nodes: 1
mem_per_gpu: null
mem_per_cpu: 64G
account: ls_krausea
name: ${hydra.job.name}
constraint: null # rtx_4090
array_parallelism: 256
# gres: gpumem:32g
additional_parameters:
  gpus: rtx_4090:1 # replace this with the gpu mem via gres
  # gpus: 1
  account: ls_krausea
