# @package _global_

#for HPO runs.
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: submitit_slurm
  - override /hydra/sweeper/sampler: grid

## Specify multiple metrics and how they should be added together
metrics_to_optimize:
  rmse_average: 1.0
  rmse_rank_average: 0.1

hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    # direction: minimize
    study_name: ${model._target_}_${oc.env:USER}_${now:%Y-%m-%d}/${now:%H-%M-%S} # if there is an existing study with the same name, it will be resumed
    storage: null
    n_trials: 100  # number of total trials
    n_jobs: 100 # number of parallel jobs
    params:
      # model.n_layers: range(1, 3, step=2)
      model.encoder_width: choice(1280, 2304, 5376)
      model.latent_dim: choice(64, 192, 256, 512)
      seed: choice(0, 245)